---
abstract: 'An Event Log Debug Panel'
author:
  - 'Nikolay Martynov, C<< <kolya at cpan.org> >>'
  - 'Nikolay Martynov <kolya@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::CheckManifest: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
  Module::Install: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-Debug-Timed-Logger
no_index:
  directory:
    - inc
    - t
requires:
  Plack::Middleware::Debug: 0
  Plack::Middleware::Timed::Logger: 0
  perl: 5.16.0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Plack-Middleware-Debug-Timed-Logger
  license: http://dev.perl.org/licenses/
version: 0.0.3
